[Bug/#141] 카테고리 변경시 상단으로 스크롤
DeveloperAcademy-POSTECH/MacC-Team16-ABloom pull request #142
Opened 2023-11-04 08:50 UTC by Hayun218

#### close #141

### ✏️ 개요
- 질문선택뷰에서 카테고리 변경 시 스크롤이 유지되는 현상 해결

### 💻 작업 사항
- ScrollViewReader 도입으로 카테고리가 변경될 경우, 상단으로 이동하도록 해결
- padding 값 피그마 보고 눈대중으로 재조정
- bottom 부분에 패딩 추가하여 사용성 부분 개선

### 📄 리뷰 노트
onChange에 new 값을 안 적으면, 17버전에서만 사용되는 함수라고 되어서, 안쓰는 변수이지만 기존 onChange 함수에서 쓰는 것처럼 추가해 두었습니다.

### 📱결과 화면(optional)
![Simulator Screenshot - iPhone 15 Pro - 2023-11-04 at 17 49 21](https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/44897331/a899a8fb-38a3-4f17-87cb-44a877fa7408)

### 📚 ETC(optional)
X

2023-11-04 16:05 UTC, seunggyun-jeong approved these changes
긋긋! 근데 왜 패딩 값이 눈대중으로 변경인가요..?

2023-11-05 09:10 UTC, Hayun218 commented
> 긋긋! 근데 왜 패딩 값이 눈대중으로 변경인가요..?

피그마 값 그대로 반영했었는데, 피그마와 비교했을 때 간격이 더 좁았습니다~

2023-11-05 15:27 UTC, seunggyun-jeong commented
> > 긋긋! 근데 왜 패딩 값이 눈대중으로 변경인가요..?
> 
> 피그마 값 그대로 반영했었는데, 피그마와 비교했을 때 간격이 더 좁았습니다~

왜 그런 일이...

2023-11-05 16:13 UTC, JINi0S requested changes

2023-11-05 16:13 UTC, JINi0S commented on ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
> +        .padding(.bottom, 50)
패딩으로 여백을 주면 아래가 잘리네요! Spacer()로 변경해보면 어떨까요?!

<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/100195563/95b457c0-af0c-4b95-8dca-79418bf72cf7" width = "240">

2023-11-06 00:05 UTC, Hayun218 commented on ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
> +        .padding(.bottom, 50)
그 위에 캡쳐한 사진이 제가 확인하고 올린건데, 한번 다시 확인해볼게요!

2023-11-06 00:08 UTC, Hayun218 commented on ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
> +        .padding(.bottom, 50)
코드 돌려서 확인했는데 문제없습니다~

![Simulator Screenshot - iPhone 15 Pro - 2023-11-06 at 09 08 04](https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/44897331/6f826214-8783-4d2b-ad24-291cf171bf79)

2023-11-06 08:23 UTC, JINi0S commented on ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
> +        .padding(.bottom, 50)
@Hayun218 스크롤은 안하고 카테고리만 변경했을 때 하단이 짤리는 경우를 말한 겁니다! 다시 확인해주실 수 있나욥??

2023-11-06 13:09 UTC, Hayun218 commented on ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
> +        .padding(.bottom, 50)
오호랏! 확인하고 수정해서 커밋올려두겠습니다!

2023-11-06 13:22 UTC, Hayun218 commented
라딘이 말한 사항 수정했습니다!! 확인 감사합니다 :)
스크롤뷰 외부에 Spacer를 추가해도 동일한 상황이 발생했고, 스크롤뷰의 마지막일 때 그 내부에서 공백을 주어야 저희가 의도한 데로 나왔습니다!
그래서 if 문으로 리스트의 마지막 질문일 때 추가하도록 수정하여 커밋 올렸습니다~

2023-11-06 14:26 UTC, JINi0S commented
> 라딘이 말한 사항 수정했습니다!! 확인 감사합니다 :) 스크롤뷰 외부에 Spacer를 추가해도 동일한 상황이 발생했고, 스크롤뷰의 마지막일 때 그 내부에서 공백을 주어야 저희가 의도한 데로 나왔습니다! 그래서 if 문으로 리스트의 마지막 질문일 때 추가하도록 수정하여 커밋 올렸습니다~

ForEach문 다음에 Spacer() 주면 if문 안써도 될 듯 합니다! ForEach문 상단에 Spacer()있는 것처럼요!! 😶‍🌫️😶‍🌫️

2023-11-06 14:26 UTC, JINi0S approved these changes

2023-11-06 14:35 UTC, Hayun218 commented
> > 라딘이 말한 사항 수정했습니다!! 확인 감사합니다 :) 스크롤뷰 외부에 Spacer를 추가해도 동일한 상황이 발생했고, 스크롤뷰의 마지막일 때 그 내부에서 공백을 주어야 저희가 의도한 데로 나왔습니다! 그래서 if 문으로 리스트의 마지막 질문일 때 추가하도록 수정하여 커밋 올렸습니다~
> 
> ForEach문 다음에 Spacer() 주면 if문 안써도 될 듯 합니다! ForEach문 상단에 Spacer()있는 것처럼요!! 😶‍🌫️😶‍🌫️

그렇게 했었는데, VStack 으로 전체가 감싸져있고 그 내부에 스크롤이 있는 형태다 보니, 위에 Spacer 있는게 움직일 때 고정되어 있는 것처럼 아래에도 고정적으로 있어서 저렇게 구현했습니다!

2023-11-06 14:38 UTC, merged