[Feat/#327] 문답완성 알림 수정
DeveloperAcademy-POSTECH/MacC-Team16-ABloom pull request #335
Opened 2024-03-20 15:56 UTC by Hayun218

#### close #327

### ✏️ 개요
문답 완성 시 알림 로직 수정 및 is_completed 필드 업데이트 함수 추가

### 💻 작업 사항
- 리액션이 둘 다 긍정일 때, is_completed 필드를 true로 변경 / 나머지의 경우에는 false로 변경
- is_completed 필드가 false에서 true로 바뀔 시, 상대방과 나에게 문답이 완성 되었음을 알리는 알림

### 📄 리뷰 노트
is_completed를 변환시키는 함수는 기존 구현되어 있는 함수를 활용했습니다.

<기획 - 지라 댓글에도 표기>
기존 완성 알림과 로직이 바뀐 부분이 있어서 기획 쪽과 상의가 필요합니다!
바뀐 부분은 아래와 같습니다.

1. 문답 완성 시 나와 상대방에게 동시에 알림 => 기존에는 상대방에게만 알림 
(변경사유: 개발하면서 확인용으로 구현했었는데, 이렇게 둘 다에게 알림이 오는 방식도 고려하면 좋을 듯 하여 그대로 남김)

2. is_completed 필드가 리액션이 수정될 때마다 업데이트가 되는 로직으로 구현되어 있어서 한번 완성 되어 알림이 간 이후에도 리액션이 수정되어 미완성에서 다시 완성이 될 경우 같은 문답에서 완성 알림이 다시 발송됨 
(변경사유: 사용자가 리액션을 실수로 눌렀을 경우나 중간에 수정하고 다시 바꿀 수도 있음을 고려하였을 때, 완성 될 때마다 알림을 주는 것이 자연스럽다고 생각함. => is_completed 필드를 전환하는 함수를 한번 true가 된 이후에는 업데이트가 되지 않도록 코드 상에서 막을 수 있음)

1번과 2번 관련하여 결정된 사항 알려주시면 적용하겠습니다!

### 📱결과 화면(optional)
<img src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/44897331/13fa934f-d11d-4622-afdc-92859c2c3240.png" width="300"/>

### 📚 ETC(optional)
X

2024-03-23 19:44 UTC, JINi0S requested changes
수정되면 좋을 것 같아서 리뷰 쪼끔 남겨요!!! 코멘트 확인해주세욥 리아-!

메서드명을 더 분명하게 했어야 했는데 혼란을 드린 것 같네요ㅠ
여유있을 때 문답확인뷰, 문답리스트뷰에 주석달기&변수명 바꾸기 캠패인을 해볼게요..같이 해봐요....

험악한 코드 확인하느라 고생 많았씁니다-!

2024-03-23 19:44 UTC, JINi0S commented on ABloom/ABloom/Presentation/Main/CheckAnswer/CheckAnswerViewModel.swift
> +    }
메서드명 때문에 헷갈렸을 것 같은데 문답완료 필드를 업데이트하는 로직은 반응을 남긴 이후가 더 적절할 것 같아요!
224줄의 updateReaction() 내부에서 수행하면 어떨까요??

그리고 상대방 앤써에도 updateAnswerComplete()해주면 isComplete 필드를 다시 잘 활용할 수 있을 것 같아요!-! 🤩

2024-03-26 12:34 UTC, seunggyun-jeong approved these changes
라딘이 이야기 한 부분만 수정하면 될 것 같습니다!

2024-03-28 05:35 UTC, Hayun218 commented
JS 로직은 아직 남았는데, Swift 코드는 수정 완료했습니다! js 쪽은 저녁에 작업 가능한데 바로 Firebase function 서버로 올라가서 적용되서 TestFlight 먼저 작업하고 있어도 됩니다. Review 부탁드려요~

2024-03-28 05:56 UTC, JINi0S approved these changes

2024-03-28 06:50 UTC, merged