[Bug/#346] 반응 수정 적용
DeveloperAcademy-POSTECH/MacC-Team16-ABloom pull request #347
Opened 2024-04-02 01:50 UTC by Hayun218

#### close #346

### ✏️ 개요
알림 기능을 위해서 작성한 코드로 인해 뷰에서 반응이 수정되지 않는 버그 수정

### 💻 작업 사항
DB 업데이트하는 순서를 교환하여 해결

2024-04-02 06:17 UTC, JINi0S requested changes
문답확인뷰 로직이 복잡한 만큼 테스트의 필요성이 느껴지네요 ㅎ,ㅎ...
아래 확인해서 수정부탁드려요!-!

-
브레이크포인트 찍어보면 219줄 guard문에서 리턴되는거 확인해볼 수 있을 거예요.
상대방 리액션이 없는 상태에서 내 리액션 추가하는 경우를 고려해서, 로직의 순서를 고민해봐도 좋을 것 같아요.

fianceAnswerId가 이전에 사용되지 않던 변수여서 nil값으로 들어오는지 확인해봤는데, answer 컬렉션을 초기에 가져올 때는 answerId에 값이 없어서 224줄에서도 리턴되더라고요.
AnswerManager에서 `fetchFianceAnswers`, `addSnapshotListenerForFianceAnswer` 메서드 확인해서 리스너 붙이기 전에도 answerId에 값 대입해주면 좋을 것 같아요!-!

그리고 git flow 방식으로 따르기로 한 만큼 release로 머지되도록 base브랜치를 수정하면 어떨까요???

2024-04-02 08:40 UTC, Hayun218 commented
1. 상대방 리액션이 없는 상태에는 내 리액션도 DB에 저장이 안되고 있었군요,, 상대방이 있는 경우만 예제로 잡고 해서 놓쳤나봐요. 확인 감사합니다 :-)
2. 아항,, 저 변수가 기존에 정의되어 있고, 다른 함수에서 쓴 걸로 보고 넣었는데 변수 다시 확인해보겠습니다!! 
3. 다른 PR에 있는 js 코드가 실제 기능에 영향은 없는데, 코드 상에서는 같이 움직이는게 좋을 것 같아서 develop에서 따서 했었어요! release에 넣는 PR이랑 같이 있었는데 아직 review가 안되어있어요 (제가 넘 늦게 올려서,, 죄송함다 ㅠㅠ) JS 코드 머지하고 release에 올린 후에 지금 이 작업 release에서 진행해도 괜찮을까요??

2024-04-02 09:14 UTC, JINi0S commented
> 1. 상대방 리액션이 없는 상태에는 내 리액션도 DB에 저장이 안되고 있었군요,, 상대방이 있는 경우만 예제로 잡고 해서 놓쳤나봐요. 확인 감사합니다 :-)
> 2. 아항,, 저 변수가 기존에 정의되어 있고, 다른 함수에서 쓴 걸로 보고 넣었는데 변수 다시 확인해보겠습니다!!
> 3. 다른 PR에 있는 js 코드가 실제 기능에 영향은 없는데, 코드 상에서는 같이 움직이는게 좋을 것 같아서 develop에서 따서 했었어요! release에 넣는 PR이랑 같이 있었는데 아직 review가 안되어있어요 (제가 넘 늦게 올려서,, 죄송함다 ㅠㅠ) JS 코드 머지하고 release에 올린 후에 지금 이 작업 release에서 진행해도 괜찮을까요??

3번 좋습니다!-!

2024-04-02 17:44 UTC, Hayun218 commented
1. 상대방 리액션이 없는 경우는 `is_complete` 필드에 대해 따로 작업이 필요없어서, 자연스럽게 return 되도록 순서만 변경했습니다.

2. 이리저리 봤는데.. 일단 정리해서 적어봅니다.

ViewModel 파일 내부에 있는 `getFianceAnswer()` 함수에서 AnswerManager의 `addSnapshotListenerForFianceAnswer`를 통해 저장된 `fianceAnswer`를 sink하여 `fianceAnswer`, `fianceAnswerId` 정보를 추출합니다. 이 때, 라딘이 말한 것처럼 `fianceAnswerId`이 계속 nil 이어서 결국 guard let 에 잡히는 걸 확인했습니다. `addSnapshotListenerForFianceAnswer` 내부에서 확인했을 때는, id 값도 잘 들어갔는데, sink된 변수에서는 처리가 안되어 있더라고요.. 결론적으로 answer 자체는 잘 저장되어 content는 불러와지는데, id 만 nil로 되는 상황이었습니다.

`리스너 붙이기 전에도 answerId에 값 대입` 을 해볼려고 했는데, answerId는 Document id 여서 현재는 스냅샷리스너 안에 있는 map을 통해서만 값에 접근해 변수에 저장되어 있었습니다. nil을 방지하고자 임의로 넣어주는건 안될 거 같고, 문서에 접근해서 넣는 함수를 구현할 수 있는데, 그렇다면 `addSnapshotListenerForFianceAnswer()` 를 실행하도록 하면 어떨까 해서 `init()`  으로 추가했고 결론적으로 변수 내에 id 값도 잘 들어가서 기능은 구현이 됩니다 (view에서 .task() 내부에서 실행하는 것과 결과는 동일).

급하게 처리한다고 이렇게 구현은 했는데, 전체적으로 주석 처리와 리스너 쓰는게 이게 맞는지 모르겠어서,, 쭈욱 정리하는 시간 가져도 좋을 것 같아요 ㅎ 

3. JS 코드 아직 승인이 안되서 일단 이 PR 베이스는 release로 변경해두었습니다!

2024-04-03 02:33 UTC, JINi0S commented
> 1. 상대방 리액션이 없는 경우는 `is_complete` 필드에 대해 따로 작업이 필요없어서, 자연스럽게 return 되도록 순서만 변경했습니다.
> 2. 이리저리 봤는데.. 일단 정리해서 적어봅니다.
> 
> ViewModel 파일 내부에 있는 `getFianceAnswer()` 함수에서 AnswerManager의 `addSnapshotListenerForFianceAnswer`를 통해 저장된 `fianceAnswer`를 sink하여 `fianceAnswer`, `fianceAnswerId` 정보를 추출합니다. 이 때, 라딘이 말한 것처럼 `fianceAnswerId`이 계속 nil 이어서 결국 guard let 에 잡히는 걸 확인했습니다. `addSnapshotListenerForFianceAnswer` 내부에서 확인했을 때는, id 값도 잘 들어갔는데, sink된 변수에서는 처리가 안되어 있더라고요.. 결론적으로 answer 자체는 잘 저장되어 content는 불러와지는데, id 만 nil로 되는 상황이었습니다.
> 
> `리스너 붙이기 전에도 answerId에 값 대입` 을 해볼려고 했는데, answerId는 Document id 여서 현재는 스냅샷리스너 안에 있는 map을 통해서만 값에 접근해 변수에 저장되어 있었습니다. nil을 방지하고자 임의로 넣어주는건 안될 거 같고, 문서에 접근해서 넣는 함수를 구현할 수 있는데, 그렇다면 `addSnapshotListenerForFianceAnswer()` 를 실행하도록 하면 어떨까 해서 `init()` 으로 추가했고 결론적으로 변수 내에 id 값도 잘 들어가서 기능은 구현이 됩니다 (view에서 .task() 내부에서 실행하는 것과 결과는 동일).
> 
> 급하게 처리한다고 이렇게 구현은 했는데, 전체적으로 주석 처리와 리스너 쓰는게 이게 맞는지 모르겠어서,, 쭈욱 정리하는 시간 가져도 좋을 것 같아요 ㅎ
> 
> 3. JS 코드 아직 승인이 안되서 일단 이 PR 베이스는 release로 변경해두었습니다!

init할때 스냅샷 리스너를 붙이면 새로운 문답을 확인할 때마다 리스너가 추가되고, 리스너 안의 로직이 반복적으로 실행돼서 비효율적일 것 같아요!! 지금 리스너도 문서에서 변경된 것만 불러오는 게 아니라 문답 전체를 불러오기 때문에 불필요한 읽기작업이 많이 생길 수도 있을 것 같단 생각입니다!

`deinit 메서드 추가`, `문답리스트뷰에서 addSnapshotListenerForFianceAnswer 실행` 등의 방법도 있겠지만, 
 `fetchFianceAnswers`에서 처음 문답을 불러올 때 answerId를 추가할 수 있도록 수정된다면 더 좋을 것 같아요! 확인해보고 수정부탁드려욥 😶‍🌫️

<img width="489" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/100195563/a6274e13-47d4-4d50-a725-74ed7c3e787e">

2024-04-03 11:07 UTC, Hayun218 commented
아하! fetch 함수 내부에서 answerID 대입해주면 바로 적용이 되는군요,, 라딘 직접 구현 감사해요 ㅠㅠ
리스너를 처음 앱 구동시 바로 불러서 붙여주는데, 왜 변수에 안들어가는지 어디에서 놓쳤는지 이해가 안됐었어요;; 적용했고 잘 동작되는거 확인했습니다!

2024-04-03 14:19 UTC, seunggyun-jeong approved these changes
훌륭한 논의들이 있었군요... 자세히 살펴보지는 못해서 죄송합니다. 라딘이 잘해주신 것 같네요! 감사합니다!

2024-04-03 14:34 UTC, JINi0S approved these changes

2024-04-04 01:03 UTC, merged