[Design/59] QuestionView 디자인 수정 및 완료
DeveloperAcademy-POSTECH/MacC-Team16-ABloom pull request #65
Opened 2023-10-27 15:05 UTC by Hayun218

#### close #59

### ✏️ 개요
- Question 탭에 연결되어 있는 3개의 뷰 디자인 수정 (WriteView는 이전에 수정함)

### 💻 작업 사항
- [X] QuestionMainView에서 비치되는 이미지 세도우 값 조정 (벤틀리와 차후 논의 필요)
- [X] SelectQuestionView에서 backWall 전체 화면으로 조정, padding 값 조정
- [X] AnswerCheckView에서 padding 값 조정
- [X] backWall에 해당하는 blur 값 조절하여 피그마와 어느정도 맞춤
- [X] Customized Navigation에 패딩(10) 추가 (피그마에서 값이 10)
- [X] 폰트 모디파이어에서 라인 스페이싱 파라미터 추가
- [X] [Bug] New Group에 해당하는 코드 삭제

### 📄 리뷰 노트
컴포넌트는 우선 제가 사용하는 뷰에서 조절하였습니다. 
다음 이슈 때는 챗 버블과 쉐도우 포함 전반적인 컴포넌트를 수정하도록 하겠습니다. :)

Bentley -> 이미지에 inner shadow를 덮는 과정을 완료하지 못했습니다. 이미지 자체 배경 칼라에 쉐도우를 입히기 위해서 여러방법으로 시도했지만 찾지 못해 다른 방안을 모색, 지금 shadow로 지정, 혹은 둘 사이의 합의점을 찾으면 좋을 것 같습니다.

### 📱결과 화면(optional)
| Main | Question | AnswerCheck |
|--------|--------|--------|
| ![Main](https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/44897331/53145c7a-539d-48bd-95eb-7f5925cd678b) | ![Question](https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/44897331/23f7ea7c-cce2-4abc-bbff-c25f91a5bcb2) | ![Check](https://github.com/DeveloperAcademy-POSTECH/MacC-Team16-ABloom/assets/44897331/b2eef301-b528-4250-8db1-d6e0afce047c) |
 
### 📚 ETC(optional)
X

2023-10-27 17:42 UTC, JINi0S requested changes
SelectQuestionView에 남긴 피드백은 수정부탁드립니다! 🫠
고생해써요 리아!

2023-10-27 17:42 UTC, JINi0S commented on ABloom/ABloom/Presentation/CoreViews/QnA/View/SelectQuestionView.swift
>            }
```swift
NavigationLink(value: question) {
    LeftBlueChatBubble(text: question.content)
}
.padding(.horizontal, 20)
.padding(.bottom, 12)
``` 
이부분도 수정된다면 패딩으로된 여백을 클릭했을 때 화면이동을 방지할 수 있을 것 같아요!

2023-10-27 17:42 UTC, JINi0S commented on ABloom/ABloom/Resources/Components/QnAListItem.swift
>      .padding([.leading, .trailing], 20)
```suggestion
    .padding(.horizontal, 20)
```
수정되면 좋을 것 같습니다!

이부분도 상위뷰에서 패딩을 주는 방식을 고려해봐도 좋을 듯 합니다 🌝

2023-10-27 17:42 UTC, JINi0S commented on ABloom/ABloom/Presentation/CoreViews/QnA/View/QuestionMainView.swift
> +      }
```suggestion
      NavigationLink(value: 0) {
        Image("pencil_write_fill")
      }
      .padding([.trailing], 17)
```
이렇게 수정하면 패딩으로된 여백을 클릭했을 때 화면이동되는 것을 방지할 수 있을 것 같아요!

2023-10-28 08:33 UTC, kimyejoon commented
이미지에 inner shadow 안 들어가는 이슈 확인했어요! 공유해주셔서 감사합니다 리아 👏🏻 스크린샷 올려주신 것으로 확인해볼 때 크리티컬 이슈라고는 판단되지 않아서, 우선 이렇게 진행해주셔도 좋을 것 같아요 고생하셨어요 !!

2023-10-28 13:36 UTC, Hayun218 commented
라딘 리뷰 적용해서 올려두었습니다. :)

추가로 쉐도우 함수들이 활용 유무를 주석으로 표기해 두었습니다.
라딘이 이전에 .drop 쉐도우는 밖으로 빼서 진행한다고 표기해 두었는데, 육안상 확인했을 때 피그마와 비슷해서 그런걸까요? 0.0

2023-10-28 14:19 UTC, JINi0S commented
> 라딘 리뷰 적용해서 올려두었습니다. :)
> 
> 추가로 쉐도우 함수들이 활용 유무를 주석으로 표기해 두었습니다. 라딘이 이전에 .drop 쉐도우는 밖으로 빼서 진행한다고 표기해 두었는데, 육안상 확인했을 때 피그마와 비슷해서 그런걸까요? 0.0

안에서 했을 때 적용된게 안보여서 빼야된다고 생각하고 빼고 작업했었는데,
리아가 지운거 보고 다시 확인해보니까
수정된 수치를 다시 안에 넣었을 때 화면이 동일하더라구요,,! 수치가 문제였나봅니다 😅

2023-10-28 14:20 UTC, JINi0S approved these changes

2023-10-29 05:31 UTC, seunggyun-jeong approved these changes
확인했습니다~! 고생하셨어요

2023-10-29 05:50 UTC, merged